name: blog_app_project
description: A blog application

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  google_fonts: ^2.0.0
  # firebase sdks
  firebase_auth: ^1.0.0
  firebase_core: ^1.0.0
  cloud_firestore: ^1.0.0
  firebase_storage: ^8.0.0
  fimber: ^0.5.0-nullsafety.1
  json_annotation: ^4.0.0
  flutter_tabler_icons: ^1.0.3-rc.1
  shared_preferences: ^2.0.5
  flutter_riverpod: ^0.13.1
  equatable: ^2.0.0
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  build_runner: ^1.11.5
  json_serializable: ^4.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/sample/
