name: apps
description: A Flutter News App

publish_to: 'none'

version: 0.0.1+001

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  reading_time: ^1.0.0+2
  share: ^0.6.4+2
  shared_preferences: ^0.5.10
  sliding_sheet: ^0.3.3
  super_enum: ^0.5.0
  json_annotation: ^3.0.1
  jiffy: ^3.0.1
  google_sign_in: ^4.5.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  image_cropper: ^1.2.1
  image_picker: ^0.6.1+10
  google_fonts: ^1.1.0
  flutter_spinkit: ^4.1.2+1
  flutter_bloc: ^6.1.1
  flutter_dotenv: ^3.0.2
  flutter_icons: ^1.0.0+1
  flutter_image_compress: ^0.6.5+1
  flutter_local_notifications: ^3.0.3
  flutter_rating_bar:
  flutter_staggered_animations: ^0.1.2
  flutter_staggered_grid_view: ^0.3.0
  flutter_riverpod: ^0.12.1
  dio: ^3.0.10
  bloc: ^6.1.1
  cached_network_image: ^2.3.2+1
  carousel_slider: ^2.1.0
  circular_reveal_animation: ^1.1.5
  palette_generator:
  connectivity: ^2.0.2
  path_provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  auto_route_generator: ^0.6.8
  bloc_test: ^7.1.0
  build_runner: ^1.10.10
  flutter_launcher_icons: ^0.7.5
  flutter_launcher_name: ^0.0.1
  hive_generator: ^0.8.2
  json_serializable: ^3.2.0
  logger: ^0.9.4
  mockito: ^4.1.3
  pedantic: ^1.9.2
  super_enum_generator: ^0.6.0

# app icon
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/logo.png"

# app name
flutter_launcher_name:
  name: "Flutter News App"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/img/
    - assets/json/
    - .env





























